# Basic
title: Joseph Meng
subtitle: Joseph Meng's personal blog
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About me, description: About me, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 你的牌打得也忒儿好了
    github: JosephMLX
    twitter: MENG_LINGXU
    linkedin: Meng Lingxu
    instagram: lingxumeng
    mail: menglingxu95@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
